<a href="https://colab.research.google.com/github/VaishnaviP0707/Python/blob/main/example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [11]:
data = {
    'Country': ['France', 'Spain', 'Germany', 'Spain', 'Germany', 'France', 'Spain', 'France', 'Germany', 'France'],
    'Colour': ['Red', 'Yellow', 'Blue', 'Pink', 'Green', 'Red', 'Yellow', 'Blue', 'Pink', 'Green'],
    'Age': [44, 27, 30, 38, 40, 35, None, 48, 50, 37],
    'Salary': [72000, 48000, 54000, 61000, None, 58000, 52000, 79000, 83000, 67000],
    'Purchased': ['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes']
}

# Create a DataFrame from the data
df = pd.DataFrame(data)

# Print the DataFrame
print(df)

   Country  Colour   Age   Salary Purchased
0   France     Red  44.0  72000.0        No
1    Spain  Yellow  27.0  48000.0       Yes
2  Germany    Blue  30.0  54000.0        No
3    Spain    Pink  38.0  61000.0        No
4  Germany   Green  40.0      NaN       Yes
5   France     Red  35.0  58000.0       Yes
6    Spain  Yellow   NaN  52000.0        No
7   France    Blue  48.0  79000.0       Yes
8  Germany    Pink  50.0  83000.0        No
9   France   Green  37.0  67000.0       Yes


In [12]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [13]:
X

array([['France', 'Red', 44.0, 72000.0],
       ['Spain', 'Yellow', 27.0, 48000.0],
       ['Germany', 'Blue', 30.0, 54000.0],
       ['Spain', 'Pink', 38.0, 61000.0],
       ['Germany', 'Green', 40.0, nan],
       ['France', 'Red', 35.0, 58000.0],
       ['Spain', 'Yellow', nan, 52000.0],
       ['France', 'Blue', 48.0, 79000.0],
       ['Germany', 'Pink', 50.0, 83000.0],
       ['France', 'Green', 37.0, 67000.0]], dtype=object)

In [14]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [16]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 2:4])
X[:, 2:4] = imputer.transform(X[:, 2:4])
X

array([['France', 'Red', 44.0, 72000.0],
       ['Spain', 'Yellow', 27.0, 48000.0],
       ['Germany', 'Blue', 30.0, 54000.0],
       ['Spain', 'Pink', 38.0, 61000.0],
       ['Germany', 'Green', 40.0, 63777.77777777778],
       ['France', 'Red', 35.0, 58000.0],
       ['Spain', 'Yellow', 38.77777777777778, 52000.0],
       ['France', 'Blue', 48.0, 79000.0],
       ['Germany', 'Pink', 50.0, 83000.0],
       ['France', 'Green', 37.0, 67000.0]], dtype=object)

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
import numpy as np

# Sample data
data = np.array([[1, 'red', 10],
                 [2, 'green', 20],
                 [3, 'blue', 30]])

# Define transformers for numerical and categorical columns
numeric_transformer = Pipeline(steps=[
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder())
])

# Specify which columns should be processed by which transformers
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, [0, 2]),  # apply scaler to columns 0 and 2
        ('cat', categorical_transformer, [1])  # apply one-hot encoder to column 1
    ])

# Apply transformations
transformed_data = preprocessor.fit_transform(data)
print(transformed_data)

[[-1.22474487 -1.22474487  0.          0.          1.        ]
 [ 0.          0.          0.          1.          0.        ]
 [ 1.22474487  1.22474487  1.          0.          0.        ]]


In [11]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Sample categorical data
data = np.array([['red'], ['green'], ['blue'], ['red'], ['blue']])

# Create the OneHotEncoder object
encoder = OneHotEncoder()

# Fit and transform the data
one_hot_encoded_data = encoder.fit_transform(data)

# Print the one-hot encoded data
print(one_hot_encoded_data.toarray())

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
